/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'hotel' : null } |
  { 'museum' : null } |
  { 'park' : null } |
  { 'beach' : null } |
  { 'landmark' : null } |
  { 'restaurant' : null };
export interface Review {
  'id' : bigint,
  'reviewerName' : string,
  'comment' : string,
  'locationId' : bigint,
  'timestamp' : Time,
  'rating' : bigint,
}
export type Time = bigint;
export interface TouristLocation {
  'id' : bigint,
  'country' : string,
  'directions' : string,
  'city' : string,
  'name' : string,
  'description' : string,
  'averageRating' : number,
  'imageUrl' : string,
  'address' : string,
  'category' : Category,
  'reviewCount' : bigint,
}
export interface _SERVICE {
  'addLocation' : ActorMethod<
    [string, string, Category, string, string, string, string, string],
    bigint
  >,
  'addReview' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'filterByCategory' : ActorMethod<[Category], Array<TouristLocation>>,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllLocations' : ActorMethod<[], Array<TouristLocation>>,
  'getLocation' : ActorMethod<[bigint], [] | [TouristLocation]>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'isSeeded' : ActorMethod<[], boolean>,
  'searchLocations' : ActorMethod<[string], Array<TouristLocation>>,
  'seedDantewadaData' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];