/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'hotel' : IDL.Null,
  'museum' : IDL.Null,
  'park' : IDL.Null,
  'beach' : IDL.Null,
  'landmark' : IDL.Null,
  'restaurant' : IDL.Null,
});
export const TouristLocation = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Text,
  'directions' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'averageRating' : IDL.Float64,
  'imageUrl' : IDL.Text,
  'address' : IDL.Text,
  'category' : Category,
  'reviewCount' : IDL.Nat,
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'id' : IDL.Nat,
  'reviewerName' : IDL.Text,
  'comment' : IDL.Text,
  'locationId' : IDL.Nat,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addLocation' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addReview' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
  'filterByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(TouristLocation)],
      ['query'],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllLocations' : IDL.Func([], [IDL.Vec(TouristLocation)], ['query']),
  'getLocation' : IDL.Func([IDL.Nat], [IDL.Opt(TouristLocation)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'isSeeded' : IDL.Func([], [IDL.Bool], ['query']),
  'searchLocations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TouristLocation)],
      ['query'],
    ),
  'seedDantewadaData' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'hotel' : IDL.Null,
    'museum' : IDL.Null,
    'park' : IDL.Null,
    'beach' : IDL.Null,
    'landmark' : IDL.Null,
    'restaurant' : IDL.Null,
  });
  const TouristLocation = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Text,
    'directions' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'averageRating' : IDL.Float64,
    'imageUrl' : IDL.Text,
    'address' : IDL.Text,
    'category' : Category,
    'reviewCount' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'id' : IDL.Nat,
    'reviewerName' : IDL.Text,
    'comment' : IDL.Text,
    'locationId' : IDL.Nat,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'addLocation' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addReview' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Nat], [], []),
    'filterByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(TouristLocation)],
        ['query'],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllLocations' : IDL.Func([], [IDL.Vec(TouristLocation)], ['query']),
    'getLocation' : IDL.Func([IDL.Nat], [IDL.Opt(TouristLocation)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'isSeeded' : IDL.Func([], [IDL.Bool], ['query']),
    'searchLocations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TouristLocation)],
        ['query'],
      ),
    'seedDantewadaData' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };