/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TouristLocation {
    id: bigint;
    country: string;
    directions: string;
    city: string;
    name: string;
    description: string;
    averageRating: number;
    imageUrl: string;
    address: string;
    category: Category;
    reviewCount: bigint;
}
export interface Review {
    id: bigint;
    reviewerName: string;
    comment: string;
    locationId: bigint;
    timestamp: Time;
    rating: bigint;
}
export enum Category {
    hotel = "hotel",
    museum = "museum",
    park = "park",
    beach = "beach",
    landmark = "landmark",
    restaurant = "restaurant"
}
export interface backendInterface {
    addLocation(name: string, description: string, category: Category, address: string, city: string, country: string, directions: string, imageUrl: string): Promise<bigint>;
    addReview(locationId: bigint, reviewerName: string, comment: string, rating: bigint): Promise<void>;
    filterByCategory(category: Category): Promise<Array<TouristLocation>>;
    getAllCategories(): Promise<Array<string>>;
    getAllLocations(): Promise<Array<TouristLocation>>;
    getLocation(id: bigint): Promise<TouristLocation | null>;
    getReviews(locationId: bigint): Promise<Array<Review>>;
    isSeeded(): Promise<boolean>;
    searchLocations(keyword: string): Promise<Array<TouristLocation>>;
    seedDantewadaData(): Promise<void>;
}
import type { Category as _Category, TouristLocation as _TouristLocation } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLocation(arg0: string, arg1: string, arg2: Category, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addLocation(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLocation(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addReview(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async filterByCategory(arg0: Category): Promise<Array<TouristLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByCategory(to_candid_Category_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllLocations(): Promise<Array<TouristLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLocations();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLocations();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocation(arg0: bigint): Promise<TouristLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocation(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocation(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviews(arg0: bigint): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async isSeeded(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSeeded();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSeeded();
            return result;
        }
    }
    async searchLocations(arg0: string): Promise<Array<TouristLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchLocations(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchLocations(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async seedDantewadaData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDantewadaData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDantewadaData();
            return result;
        }
    }
}
function from_candid_Category_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_TouristLocation_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TouristLocation): TouristLocation {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TouristLocation]): TouristLocation | null {
    return value.length === 0 ? null : from_candid_TouristLocation_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    country: string;
    directions: string;
    city: string;
    name: string;
    description: string;
    averageRating: number;
    imageUrl: string;
    address: string;
    category: _Category;
    reviewCount: bigint;
}): {
    id: bigint;
    country: string;
    directions: string;
    city: string;
    name: string;
    description: string;
    averageRating: number;
    imageUrl: string;
    address: string;
    category: Category;
    reviewCount: bigint;
} {
    return {
        id: value.id,
        country: value.country,
        directions: value.directions,
        city: value.city,
        name: value.name,
        description: value.description,
        averageRating: value.averageRating,
        imageUrl: value.imageUrl,
        address: value.address,
        category: from_candid_Category_n6(_uploadFile, _downloadFile, value.category),
        reviewCount: value.reviewCount
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hotel: null;
} | {
    museum: null;
} | {
    park: null;
} | {
    beach: null;
} | {
    landmark: null;
} | {
    restaurant: null;
}): Category {
    return "hotel" in value ? Category.hotel : "museum" in value ? Category.museum : "park" in value ? Category.park : "beach" in value ? Category.beach : "landmark" in value ? Category.landmark : "restaurant" in value ? Category.restaurant : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TouristLocation>): Array<TouristLocation> {
    return value.map((x)=>from_candid_TouristLocation_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    hotel: null;
} | {
    museum: null;
} | {
    park: null;
} | {
    beach: null;
} | {
    landmark: null;
} | {
    restaurant: null;
} {
    return value == Category.hotel ? {
        hotel: null
    } : value == Category.museum ? {
        museum: null
    } : value == Category.park ? {
        park: null
    } : value == Category.beach ? {
        beach: null
    } : value == Category.landmark ? {
        landmark: null
    } : value == Category.restaurant ? {
        restaurant: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
